controller: Changed controller ref to owner ref
red-hat-storage/odf-operator pull request #172
Opened 2022-01-25 06:30 UTC by bindrad

issue: https://bugzilla.redhat.com/show_bug.cgi?id=2044447

fix: changed controller ref to owner ref

Signed-off-by: bindrad <dbindra@redhat.com>

2022-01-25 08:33 UTC, iamniting requested changes
Hi Dhruv, Changes looks good to me, CI is also passed, Can we pls change a commit-msg with something descriptive. eg.

```
controllers: change controller ref to owner ref of the vendor system

We are using the controller ref to show the vendor CR in the OCP UI
and can also use the owner ref for the same.
controller ref is required by the managed services as storageCluster 
is created by them in the manages services.

changing the controller ref to owner ref will solve the managed 
services problem.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2044447
```

2022-01-25 08:42 UTC, iamniting approved these changes
/lgtm

2022-01-25 09:03 UTC, merged

2022-02-08 12:06 UTC, agarwal-mudit commented
/cherry-pick release-4.10

2022-02-08 12:10 UTC, agarwal-mudit commented
No need to cherry-pick, change is already there in release-4.10