Fix ODF operator to limit leaderElection & cache to operator namespace
red-hat-storage/odf-operator pull request #260
Opened 2022-09-19 07:40 UTC by malayparida2000

Resolves-
https://bugzilla.redhat.com/show_bug.cgi?id=2092737

Currently odf-operator is relying on the default "AllNamespaces" cache in controller-runtime, which works by syncing all the Kubernetes resources in the cluster. This initial informer cache sync is so huge that it causes a sudden massive spike in the memory usage of the operator. The memory spike when not sufficient for the set memory limits, causes OOMKilled failures for the odf-operator pods.

So odf-operator will now set the leaderElectionNamespace & the Manager cache to the namespace where the operator is deployed. This will ensure that the initial cache sync will only sync the resources in the namespace where the operator is deployed.

Signed-off-by: Malay Kumar Parida <mparida@redhat.com>

2022-09-19 15:48 UTC, iamniting requested changes

2022-09-19 15:49 UTC, malayparida2000 commented on main.go
> +}
Yes, Makes Sense

2022-09-19 16:03 UTC, iamniting approved these changes
/lgtm

2022-09-19 17:10 UTC, merged

2022-10-19 08:06 UTC, iamniting commented
/cherry-pick release-4.10

2022-10-19 08:08 UTC, iamniting commented
/cherry-pick release-4.9